version: '3'
services:
  fastdfs-tracker:
    image: season/fastdfs:1.2
    container_name: fastdfs-tracker
    restart: always
    volumes:
      - "./fastdfs-data/tracker_data:/fastdfs/tracker/data"
    ports:
      - "22122:22122"
    command: "tracker"

  fastdfs-storage:
    image: season/fastdfs:1.2
    container_name: fastdfs-storage
    links:
      - fastdfs-tracker
    restart: always
    volumes:
      - "./fastdfs/storage.conf:/fdfs_conf/storage.conf"
      - "./fastdfs-data/storage_base_path:/fastdfs/storage/data"
      - "./fastdfs-data/store_path0:/fastdfs/store_path"
    ports:
      - "23000:23000"
    environment:
      TRACKER_SERVER: "fastdfs-tracker:22122"
    command: "storage"

  fastdfs-nginx:
    image: season/fastdfs:1.2
    container_name: fastdfs-nginx
    restart: always
    volumes:
      - "./fastdfs/nginx.conf:/etc/nginx/conf/nginx.conf"
      - "./fastdfs-data/store_path0:/fastdfs/store_path"
    links:
      - fastdfs-tracker
    ports:
      - "8088:8088"
    environment:
      TRACKER_SERVER: "fastdfs-tracker:22122"
    command: "nginx"

  blockchain-mysql80:
    image: mysql:8.0
    container_name: blockchain-mysql
    ports:
      - "3310:3306"
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
      - ./db/init-sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: blockchain123456
    restart: always

  blockchain-redis:
    #定义主机名
    container_name: blockchain-redis
    #使用的镜像；注意这里的版本要与第2步redis版本一致
    image: redis:6.0.6
    #容器的映射端口
    ports:
      - 6382:6379 #注意第二个端口必须是redis.conf中的端口号
    command: redis-server /etc/redis.conf
    #定义挂载点
    volumes:
      - ./data:/data #挂载/docker-compose/redis/data至容器
      - ./conf/redis.conf:/etc/redis.conf #挂载conf至容器
    privileged: true   #环境变量
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
    #docker 重启后，容器自启动
    restart: always

  blockchain:
    build:
      context: blockchain-fe
      dockerfile: Dockerfile
    container_name: blockchain-fe
    ports:
      - "8110:8080"
    volumes:
      - ./blockchain/uploadPath:/home/ruoyi/uploadPath
      - ./blockchain/logs:/home/ruoyi/logs
      - ./blockchain/backup:/backup
      - /etc/localtime:/etc/localtime
    depends_on:
      - blockchain-mysql80
    restart: always